# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Seeed产品文档
site_description: Seeed产品文档-中文
site_author: Loovee
site_url: http://seeed.wiki

# Repository
repo_name: SeeedDocument/SeeedDocument.github.io
repo_url: https://github.com/SeeedDocument/SeeedDocument.github.io

# Copyright
copyright: 'Seeedstudio 2017'

# Theme directory
theme_dir: material

# Icon
site_favicon: 'images/favicon.ico'

# Options
extra:
  feature:
    tabs: false
  palette:
    primary: light green
    accent: indigo
  social:
    - type: facebook
      link: https://www.facebook.com/seeedstudiosz/
    - type: github-alt
      link: https://github.com/SeeedDocument

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - Seeed文档中文站点介绍: 'index.md'
  
  - 平台:
    - Arduino:
      - Arduino: Arduino.md
      - Seeeduino Cloud: Seeeduino_Cloud.md
      - Seeeduino LoRAWAN: Seeeduino_LoRAWAN.md  
    - BeagleBone:
      - BeagleBone: BeagleBone.md
      - BeagleBone Green: BeagleBone_Green.md

    - Raspberry:
      - Raspberry: Raspberry.md
    - Wio:
      - Wio: Wio.md
    - LinkIt:
      - LinkIt: LinkIt.md
      - LinkIt Smart 7688: LinkIt_Smart_7688.md
    - mbed:
      - mbed: mbed.md
    - Rephone:
      - Rephone: Rephone.md
    - Respeaker:
      - Respeaker: Respeaker.md
      - Respeaker Mic Array: Respeaker_Mic_Array.md
      - Respeaker Core: Respeaker_Core.md
      - Respeaker 2-Mics Pi HAT: Respeaker_2-Mics_Pi_HAT.md  
      - Respeaker 4-Mics Pi HAT: Respeaker_4-Mics_Pi_HAT.md
    - Shield:
      - Shield: Shield.md
      - Base Shield V2: Base_Shield_V2.md
      - CAN-BUS Shield V1.2: CAN-BUS_Shield_V1.2.md
      - CAN-BUS Shield V2.0: CAN-BUS_Shield_V2.0.md
    - Essentials:
      - Essentials: Essentials.md
    - Wireless:
      - Wireless: Wireless.md
  
  - Grove:
    - Grove系统: Grove_System.md
    - 传感器:
      - Sensor: Sensor.md
      - Grove-Encoder: Grove-Encoder.md
      - Grove-Multichannel Gas Sensor: Grove-Multichannel_Gas_Sensor.md
      - Grove-Piezo Vibration Sensor: Grove-Piezo_Vibration_Sensor.md
      - Grove-Sound Sensor: Grove-Sound_Sensor.md
      - Grove-Ultrasonic Ranger: Grove-Ultrasonic_Ranger.md
      - Grove-GSR Sensor: Grove-GSR_Sensor.md
      - Grove-Dust Sensor: Grove-Dust_Sensor.md
      - Grove-Air Quality Sensor v1.3: Grove-Air_Quality_Sensor_v1.3.md
      - Grove-Barometer Sensor BMP280: Grove-Barometer_Sensor-BMP280.md
      - Grove-Ear clip Heart Rate Sensor: Grove-Ear-clip_Heart_Rate_Sensor.md
      - Grove-Gas Sensor O2: Grove-Gas_Sensor-O2.md
      - Grove-Light Sensor: Grove-Light_Sensor.md
      - Grove-MOSFET: Grove-MOSFET.md
      - Grove-Temperature Sensor: Grove-Temperature_Sensor.md
      - Grove-Temperature and Humidity Sensor Pro: Grove-Temperature_and_Humidity_Sensor_Pro.md
      - Grove-Temperature and Humidity Sensor: Grove-Temperature_and_Humidity_Sensor.md
      - Grove-Tempture and Humidity Sensor High Accuracy Mini-v1.0: Grove-TemptureAndHumidity_Sensor_High_Accuracy_AndMini-v1.0.md
      - Grove-UV Sensor: Grove-UV_Sensor.md
      - Grove-Vibration Motor: Grove-Vibration_Motor.md
      - Grove-Barometer High Accuracy: Grove-Barometer_High_Accuracy.md
      - Grove-Digital Light Sensor: Grove-Digital_Light_Sensor.md
      - Grove-Electromagnet: Grove-Electromagnet.md
      - Grove-EMG Detector: Grove-EMG_Detector.md
      - Grove-Flame Sensor: Grove-Flame_Sensor.md
      - Grove-Gas Sensor MQ9: Grove-Gas_Sensor-MQ9.md
      - Grove-HCHO Sensor: Grove-HCHO_Sensor.md
      - Grove-I2C Color Sensor: Grove-I2C_Color_Sensor.md
      - Grove-Loudness Sensor: Grove-Loudness_Sensor.md
      - Grove-Moisture Sensor: Grove-Moisture_Sensor.md
      - Grove-Temperature Sensor-V1.2: Grove-Temperature_Sensor_V1.2.md
      - Grove-Touch Sensor: Grove-Touch_Sensor.md
    
    - 执行器:
      - Actuator: Actuator.md
      - Grove-MP3-v2.0: Grove-MP3_v2.0.md
      - Grove-Infrared Receiver: Grove-Infrared_Receiver.md
      - Grove-Relay: Grove-Relay.md

    - Display:
      - Display: Display.md
      - Grove-LCD RGB Backlight: Grove-LCD_RGB_Backlight.md
      - Grove-4-Digit Display: Grove-4-Digit_Display.md

    - Communication:
      - Communication: Communication.md
    - Others:
      - Others: Others.md
      - 3W Solar Panel 138x160: 3W_Solar_Panel_138x160.md
      - Bus Pirate v3 assembled: Bus_Pirate_v3_assembled.md

  - IoT:
    - IoT: IoT.md
  
  - kit套件:
    - Grove Starter kit for Arduino 101: Grove_Starter_kit_for_Arduino_101.md
  
  - MakerPro:
    - MakerPro: MakerPro.md
    - 2KM Long Range RF link kits w encoder and decoder: 2KM_Long_Range_RF_link_kits_w_encoder_and_decoder.md
    - Piezo Sensor MiniSense 100: Piezo_Sensor-MiniSense_100.md
    - Arduboy: Arduboy.md 
  
  - 使用教程:
    - Tutorial: Tutorial.md
    - 如何安装Arduino库: How_to_install_Arduino_Library.md
    - 如何上传代码: Upload_Code.md
    - Seeeduino入门指导: Getting_Started_with_Seeeduino.md
    - 如何编辑Wiki: How_to_edit_Wiki.md
  
  - 文档协议: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
